# Changes here will be overwritten by Copier
_commit: v0.6.0
_src_path: /Users/bhklab/dev/PyPackageBuilder
author_email: jermiahjoseph98@gmail.com
author_full_name: Jermiah Joseph
build_backend: hatch
git_init: true
github_username: jjjermiah
package_description: A zero-hassle approach to metric and binary byte calculations.
package_name: bytecase
pixi_install: false
project_name: ByteCase
project_slug: bytecase
python_version: '3.10'
software_license: MIT License
